name: Semantic Search with Summarization
description: |
  Leverage Chroma vector db for semantic search and summarization in CML

author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2024-02-29"

environment_variables:
  OPENAI_KEY:
    default: "sk-xxxx"
    description: "If this is not set now, it will need to be configured for the application to function."
    required: true

  COLLECTION_NAME:
    default: "cml-default"
    description: "Enter preferred collection name for Chroma DB to store document embeddings in."
    required: true

runtimes:
  - editor: JupyterLab
    kernel: Python 3.10
    edition: Standard

tasks:

  - type: run_session
    name: Install Dependencies
    script: 0_session-install-dependencies/download_requirements.py
    short_summary: Install Package Dependencies
    kernel: python3
    cpu: 2
    memory: 8

  - type: run_session
    name: Setup Chroma Server
    script: 1_session-setup-chroma-db/setup-chroma.py
    short_summary: Setup Chroma Server Vector DB
    long_summary: Resolve sqlite dependency with python version and control logging in Chroma server package
    kernel: python3
    cpu: 2
    memory: 4

  # - type: start_application
  #   name: CML Chroma Server REST API Server
  #   subdomain: cml-chroma-server
  #   script: 2_app-run-chroma-server/launch-server.py
  #   short_summary: Launch Chroma Server
  #   long_summary: Launch Chroma Server REST API application. Vector Database creates encodings for GET and POST requests. Remember to enable unauthenticated app access for external access to the UI.
  #   cpu: 2
  #   memory: 4
  #   environment_variables:
  #     TASK_TYPE: START_APPLICATION
    
  - type: create_job
    name: Populate Chroma Vector DB with sample documents embeddings
    entity_label: chroma_vectordb_insert
    script: 3_job-populate-vectordb/chroma_vectordb_insert.py
    arguments: None
    short_summary: Create job to push vectors with document embeddings to Chroma DB. 
    cpu: 2
    memory: 8
    environment:
      TASK_TYPE: CREATE/RUN_JOB

  - type: run_job
    entity_label: chroma_vectordb_insert
    short_summary: Populate Chroma Vector DB with documents embeddings (This will only run if you set "POPULATE_SAMPLE_DATA" with "YES" as an environment variable.)

  - type: start_application
    name: CML Semantic Search Interface
    subdomain: semantic-search-ui
    script: 4_app/frontend_app.py
    short_summary: Create and start CML semantic search frontend application
    long_summary: Create and start CML semantic search frontend application. Remember to enable unauthenticated app access for external access to the UI.
    cpu: 2
    memory: 4
    environment_variables:
      TASK_TYPE: START_APPLICATION
